## REPLACE Client ID
- source:
    kind: ConfigMap
    fieldPath: data.CLIENT_ID
    name: kvmap
  targets:
  - select:
      kind: ServiceAccount
      name: serversa
    fieldPaths:
    - metadata.annotations.[azure.workload.identity/client-id]  
  - select:
      kind: SecretProviderClass  
      name: openaiapikey
    fieldPaths:
    - spec.parameters.clientID  
## REPLACE KV Name    
- source:
      kind: ConfigMap
      fieldPath: data.KV_NAME
      name: kvmap
  targets:
    - select:
       kind: SecretProviderClass
       name: openaiapikey
      fieldPaths:
      - spec.parameters.keyvaultName  
## REPLACE Tenant ID      
- source:
    kind: ConfigMap
    fieldPath: data.TENANT_ID
    name: kvmap
  targets:
  - select:
      kind: ServiceAccount
      name: serversa
    fieldPaths:
    - metadata.annotations.[azure.workload.identity/tenant-id]     
  - select:
      kind: SecretProviderClass  
      name: openaiapikey
    fieldPaths:
    - spec.parameters.tenantId     

 ## REPLACE LOCATION  ConfigMap
- source:
    kind: ConfigMap
    fieldPath: data.LOCATION
    name: kvmap
  targets:
  - select:
      kind: ConfigMap
      name: env
    fieldPaths:
    -   data.TRANSLATE_REGION
  ## REPLACE OPENAI  ConfigMap
- source:
    kind: ConfigMap
    fieldPath: data.OPENAI_API_BASE
    name: kvmap
  targets:
  - select:
      kind: ConfigMap
      name: env
    fieldPaths:
    -   data.OPENAI_API_BASE
   
  ## REPLACE OPENAI  ConfigMap
- source:
    kind: ConfigMap
    fieldPath: data.BLOB_ACCOUNT_NAME
    name: kvmap
  targets:
  - select:
      kind: ConfigMap
      name: env
    fieldPaths:
    -   data.BLOB_ACCOUNT_NAME  
   ## REPLACE OPENAI  ConfigMap
- source:
    kind: ConfigMap
    fieldPath: data.FORM_RECOGNIZER_ENDPOINT
    name: kvmap
  targets:
  - select:
      kind: ConfigMap
      name: env
    fieldPaths:
    -   data.FORM_RECOGNIZER_ENDPOINT   
 