apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mongo-secret-csi
spec:
  provider: azure
  secretObjects:
    - secretName: mongodburi    
      type: Opaque              
      data:
      - objectName: MONGODBURI
        key: MONGODBURI
  parameters:
    keyvaultName: <keyvault>   
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: <client id> # the client ID of the MSI  
    cloudName: ""                         
    objects:   |
      array:
        - |
          objectName: MONGODBURI       
          objectType: secret              
          objectVersion: ""               
    tenantId: <tenant id>
  