# Use this manifest only for the blue green deployment scenario.
apiVersion: v1
kind: Pod
metadata:
  name: test-agic-app-pod
  labels:
    app: test-agic-app
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test-agic-app-service
spec:
  selector:
    app: test-agic-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-agic-app-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: myapp-green.test.aksalzacc.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: test-agic-app-service
            port:
              number: 80
  - host: myapp.test.aksalzacc.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: test-agic-app-service
            port:
              number: 80