apiVersion: v1
kind: Namespace
metadata:
  name: simpleapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmsa
  namespace: simpleapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gmsa
  namespace: simpleapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gmsaspec-role
subjects:
- kind: ServiceAccount
  name: gmsa
  namespace: simpleapp