apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openaiapikey
  namespace: default
spec:
  parameters:
    clientID: 24c906c4-5ef0-49fa-8e6e-a2025f0ac0d9
    keyvaultName: kv-appembedingsclusterws
    objects: |
      array:
        - |
          objectName: openaiapikey
          objectType: secret
    tenantId: 449fbe1d-9c99-4509-9014-4fd5cf25b014
  provider: azure
  secretObjects:
  - data:
    - key: openaiapikey
      objectName: openaiapikey
    secretName: openaiapikey
    type: Opaque