apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openaiapikey
  namespace: default
spec:
  parameters:
    clientID: <identity clientID>
    keyvaultName: <kv name>
    objects: |
      array:
        - |
          objectName: openaiapikey
          objectType: secret
    tenantId: <tenant ID>
  provider: azure
  secretObjects:
  - data:
    - key: openaiapikey
      objectName: openaiapikey
    secretName: openaiapikey
    type: Opaque