apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
  selector:
    service: web
status:
  loadBalancer: {}
