apiVersion: v1
kind: Namespace
metadata:
  name: scaling-wt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rand-deployment
  namespace: scaling-wt
  labels:
    app.kubernetes.io/name: rand
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rand
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rand
    spec:
      containers:
      - name: randomnumbers-linux
        image: <your acr name>.azurecr.io/randomnumbers-linux:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 75m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:8080"
      nodeSelector:
       agentpool: npuser01
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rand-pdb
  namespace: scaling-wt
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: rand
---
kind: Service
apiVersion: v1
metadata:
  name: rand-service
  namespace: scaling-wt
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: rand
  ports:
  - name: http
    port: 80
    targetPort: 8080