apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rand-hpa
  namespace: scaling-wt
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rand-deployment
  targetCPUUtilizationPercentage: 30
