apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: <ACR_NAME>.azurecr.io/aci-aks-demo:latest
        resources:
         requests:
           memory: "64Mi"
           cpu: "50m"
         limits:
           memory: "128Mi"
           cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
         - name: azure
           mountPath: /mnt/azure
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
      affinity:
       nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
           matchExpressions:
           - key: type
             operator: NotIn
             values:
             - virtual-kubelet
      volumes:
       - name: azure
         csi:
           driver: file.csi.azure.com
           readOnly: false
           volumeAttributes:
             secretName: azure-secret 
             shareName: aksshare
---
apiVersion: v1
kind: Service
metadata:
 name: demoapp-svc
 labels:
   app: demoapp
spec:
 ports:
 - port: 80
 selector:
   app: demoapp
