apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: app1-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: demoapp-deploy
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50