apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen
spec:
  replicas: 10
  selector:
    matchLabels:
      app: loadgen
  strategy: {}
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while sleep 0.001; do wget -q -O- http://demoapp-svc.default.svc.cluster.local;
          done
        image: busybox
        name: busybox
        resources: {}
status: {}
