apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-front
  namespace: aks-store
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: store-front
            port:
              number: 80
        path: /front(/|$)(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: store-admin
            port:
              number: 80
        path: /admin(/|$)(.*)
        pathType: ImplementationSpecific