# Checks for broken links in the repo markdown

name: Broken Link Checker

on:
  schedule:
    - cron: 0 0 1 * * # run monthly

  workflow_dispatch: # run manually

jobs:
  repoLinkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@4a5af7cd2958a2282cefbd9c10f63bdb89982d76 # v1.5.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          # Check all markdown and html files in repo (default)
          args: './**/*.md'

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4.0.1
        with:
          title: 'Bot: Broken Links Detected in Repo'
          content-filepath: ./lychee/out.md
          labels: automated issue
